export interface Testimonial {
  name: string;
  comment: string;
  rating: number;
}

export interface Kost {
  id: number;
  name: string;
  location: string;
  latitude: number;
  longitude: number;
  price: number;
  tipe: "Putra" | "Putri" | "Campur";
  phone: string;
  image: string;
  gallery: string[];
  description: string;
  facilities: string[];
  testimonials: Testimonial[];
}

export const masterDataKost: Kost[] = [
  {
    id: 1,
    name: "Kost Singaraja",
    location: "Buleleng, Bali",
    latitude: -8.1123,
    longitude: 115.0883,
    price: 850000,
    tipe: "Campur",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=500&q=80",
    gallery: ["https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=400", "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=400"],
    description: "Kost nyaman strategis di area Buleleng, lingkungan tenang.",
    facilities: ["Kasur", "Lemari", "WiFi", "Dapur", "CCTV", "Akses 24 jam", "Parkir motor"],
    testimonials: [{ name: "Budi", comment: "Tempat bersih dan tenang.", rating: 5 }],
  },
  {
    id: 2,
    name: "Kost Eksklusif Jimbaran",
    location: "Badung, Bali",
    latitude: -8.7905,
    longitude: 115.1678,
    price: 1500000,
    tipe: "Campur",
    phone: "628123456789",
    image: "/images/testkost.jpg",
    gallery: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=400"],
    description: "Dekat area kampus, fasilitas premium dan lengkap.",
    facilities: ["Kasur", "Lemari", "AC", "TV", "WiFi", "Kamar mandi dalam", "Water heater", "Dapur", "Laundry", "CCTV", "Security", "Smart lock", "Akses 24 jam", "Parkir motor", "Parkir mobil"],
    testimonials: [{ name: "Siti", comment: "Kamar mandi dalam bersih.", rating: 5 }],
  },
  {
    id: 3,
    name: "Kost Denpasar Timur",
    location: "Denpasar, Bali",
    latitude: -8.6531,
    longitude: 115.2447,
    price: 700000,
    tipe: "Putra",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=500&q=80",
    gallery: [],
    description: "Kost khusus putra dengan harga terjangkau di Denpasar Timur.",
    facilities: ["Kasur", "Lemari", "WiFi", "Mushola", "Akses 24 jam", "Parkir motor", "Area sepeda"],
    testimonials: [{ name: "Andi", comment: "Harga bersahabat.", rating: 4 }],
  },
  {
    id: 4,
    name: "Kost Renon Estetik",
    location: "Denpasar, Bali",
    latitude: -8.6741,
    longitude: 115.2341,
    price: 1200000,
    tipe: "Putri",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1617806118233-18e1db207fa6?auto=format&fit=crop&w=500&q=80",
    gallery: [],
    description: "Kost putri aesthetic, desain minimalis modern, sangat nyaman.",
    facilities: ["Kasur", "Lemari", "AC", "WiFi", "Kamar mandi dalam", "Balkon", "Dapur", "Ruang santai", "CCTV", "Smart lock", "Parkir motor"],
    testimonials: [{ name: "Amel", comment: "Suka banget sama desain kamarnya!", rating: 5 }],
  },
  {
    id: 5,
    name: "Kost Unugasan Sunset",
    location: "Kuta Selatan, Bali",
    latitude: -8.8312,
    longitude: 115.1624,
    price: 1800000,
    tipe: "Campur",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=500&q=80",
    gallery: [],
    description: "View sunset indah langsung dari jendela kamar kost.",
    facilities: ["Kasur", "Lemari", "AC", "TV", "WiFi", "Kamar mandi dalam", "Balkon", "Dapur", "Ruang santai", "Rooftop", "CCTV", "Security", "Akses 24 jam", "Parkir motor", "Parkir mobil"],
    testimonials: [{ name: "Rian", comment: "Akses mudah ke mana-mana.", rating: 4 }],
  },
  {
    id: 6,
    name: "Kost Singaraja Asri Indah",
    location: "Buleleng, Bali",
    latitude: -8.1215,
    longitude: 115.0934,
    price: 600000,
    tipe: "Putra",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=500&q=80",
    gallery: [],
    description: "Kost putra sederhana, bersih, aman, dan sangat murah.",
    facilities: ["Kasur", "Lemari", "Dapur", "Akses 24 jam", "Parkir motor"],
    testimonials: [],
  },
  {
    id: 7,
    name: "Kost Executive Denpasar Barat",
    location: "Denpasar, Bali",
    latitude: -8.6612,
    longitude: 115.1954,
    price: 2000000,
    tipe: "Campur",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=500&q=80",
    gallery: [],
    description: "Hunian eksklusif kelas atas di pusat bisnis Denpasar Barat.",
    facilities: [
      "Kasur",
      "Lemari",
      "AC",
      "TV",
      "WiFi",
      "Kamar mandi dalam",
      "Water heater",
      "Balkon",
      "Dapur",
      "Laundry",
      "Ruang santai",
      "Mesin cuci",
      "CCTV",
      "Security",
      "Smart lock",
      "Akses 24 jam",
      "Parkir motor",
      "Parkir mobil",
      "Area sepeda",
    ],
    testimonials: [{ name: "Geri", comment: "Pelayanan mantap kelas hotel.", rating: 5 }],
  },
  {
    id: 8,
    name: "Kost Bukit Jimbaran",
    location: "Kuta Selatan, Bali",
    latitude: -8.7994,
    longitude: 115.1741,
    price: 1100000,
    tipe: "Putri",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=500&q=80",
    gallery: [],
    description: "Kost putri di area perbukitan Jimbaran yang sejuk dan asri.",
    facilities: ["Kasur", "Lemari", "AC", "WiFi", "Kamar mandi dalam", "Dapur", "Laundry", "Mushola", "CCTV", "Akses 24 jam", "Parkir motor"],
    testimonials: [],
  },
  {
    id: 9,
    name: "Kost Backpacker Kuta",
    location: "Badung, Bali",
    latitude: -8.7225,
    longitude: 115.1781,
    price: 950000,
    tipe: "Campur",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=500&q=80",
    gallery: [],
    description: "Sangat dekat ke area pantai Kuta, cocok untuk mahasiswa aktif.",
    facilities: ["Kasur", "WiFi", "Dapur", "Mesin cuci", "CCTV", "Akses 24 jam", "Parkir motor", "Area sepeda"],
    testimonials: [],
  },
  {
    id: 10,
    name: "Kost  Sanur Permai",
    location: "Denpasar, Bali",
    latitude: -8.6821,
    longitude: 115.2634,
    price: 1350000,
    tipe: "Campur",
    phone: "628123456789",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=500&q=80",
    gallery: [],
    description: "Kost tenang berasa di villa area Sanur, parkiran luas.",
    facilities: ["Kasur", "Lemari", "AC", "WiFi", "Kamar mandi dalam", "Dapur", "Rooftop", "CCTV", "Akses 24 jam", "Parkir motor", "Parkir mobil"],
    testimonials: [{ name: "Santi", comment: "Dekat banget ke pantai Sanur.", rating: 5 }],
  },
];
